name: 游 Sugerir Feature
description: Sugiere una nueva funcionalidad o mejora
title: "[FEATURE]"
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Gracias por tu sugerencia. Por favor completa el formulario para que podamos entender mejor tu idea.

  - type: input
    id: feature_summary
    attributes:
      label: Resumen de la funcionalidad
      description: Describe brevemente la funcionalidad que deseas.
      placeholder: "Ejemplo: A침adir modo oscuro"
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivaci칩n
      description: 쯇or qu칠 es 칰til esta funcionalidad?
      placeholder: "Mejorar칤a la experiencia de usuarios en ambientes con poca luz."
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
      description: 쮿as considerado otras soluciones?
      placeholder: "No, ninguna otra soluci칩n viable."
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: Informaci칩n adicional
      description: Cualquier otra informaci칩n que quieras agregar.
      placeholder: ""
      required: false
